### ISSUE TITLE
Unable to initialize integration

### ISSUE THREAD

**Issue by snah-private** [CJNE/ha-porscheconnect#243] opened 2024-06-17 09:27 UTC
The Porsche connect integration fails to initialize with the following error:

2024-06-17 11:23:55.801 ERROR (MainThread) [custom_components.porscheconnect] Un
expected error fetching porscheconnect data
Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/helpers/update_coordinator.py", lin
e 315, in _async_refresh
    self.data = await self._async_update_data()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/config/custom_components/porscheconnect/__init__.py", line 213, in _asy
nc_update_data
    vehicle["name"] = summary["nickName"] or summary["modelDescription"]
                      ~~~~~~~^^^^^^^^^^^^
KeyError: 'nickName'

**Comment by fredriklj** [comment] 2024-06-17 21:16
Duplicate of #242

**Closed by fredriklj** 2024-06-17 21:16 UTC
